services:
  - type: web
    name: berenda-backend
    runtime: node
    buildCommand: npm install --include=dev && prisma db push && prisma generate && npx tsc
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
